# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cd437671b9f7256d029abd70829d21eb73a30a0a1550b657d88330bf284ad35e770c5dc853c31ec38248da57abc7b00bd78419066ebab4f1cc4b57e809baf9e

test:
  secret_key_base: 8370cffa22e681d3cdd8a7fb8475f5b00037a31f8f42d291c9bd373b2359a084d73f54e5a8c65ce82843a6cd62892d5285b2b23858d9f6b6bc36d14d119d6c6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
